### ISSUE TITLE
DLAI6: To-do

### ISSUE THREAD

**Issue by smiile8888** [deeplearningandaiwinterschool/deeplearningandaiwinterschool.github.io#12]
- [ ] change the website's cover picture
- [x] check typos and ensure all links working (#13)
- [x] replace some speaker's pic with a  higher resolution (#13)
- [x] separate the count time JavaScript module (DLAI5 is also showing DLAI6 time) (#13)
- [x] make a registration link to open the new tab rather than refresh the main page. (#13)
